// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChjPO04asleyHxFJrI0SSCkZdkDiaEg7U',
    appId: '1:612462694102:web:fd907625ee0508027f8377',
    messagingSenderId: '612462694102',
    projectId: 'psicologia-2f688',
    authDomain: 'psicologia-2f688.firebaseapp.com',
    storageBucket: 'psicologia-2f688.firebasestorage.app',
    measurementId: 'G-94KPF3N964',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANeExWpMrJ2uEzq-45FjcecyDP4NF39LM',
    appId: '1:612462694102:android:17e7d789cd734a357f8377',
    messagingSenderId: '612462694102',
    projectId: 'psicologia-2f688',
    storageBucket: 'psicologia-2f688.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfZTo3ez8RpY9J6wA7_P9Jsty4Xtw5CJM',
    appId: '1:612462694102:ios:56161a4af74e86d57f8377',
    messagingSenderId: '612462694102',
    projectId: 'psicologia-2f688',
    storageBucket: 'psicologia-2f688.firebasestorage.app',
    iosBundleId: 'com.example.psicologia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfZTo3ez8RpY9J6wA7_P9Jsty4Xtw5CJM',
    appId: '1:612462694102:ios:56161a4af74e86d57f8377',
    messagingSenderId: '612462694102',
    projectId: 'psicologia-2f688',
    storageBucket: 'psicologia-2f688.firebasestorage.app',
    iosBundleId: 'com.example.psicologia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChjPO04asleyHxFJrI0SSCkZdkDiaEg7U',
    appId: '1:612462694102:web:565df2c59b7709147f8377',
    messagingSenderId: '612462694102',
    projectId: 'psicologia-2f688',
    authDomain: 'psicologia-2f688.firebaseapp.com',
    storageBucket: 'psicologia-2f688.firebasestorage.app',
    measurementId: 'G-3D7DQ6XWRE',
  );
}
